Traceback (most recent call last):
  File "C:\Users\jhc23\AppData\Local\Programs\Python\Python312\Lib\site-packages\myst_nb\core\execute\inline.py", line 128, in code_cell_outputs
    self._client.execute_cell(
  File "C:\Users\jhc23\AppData\Roaming\Python\Python312\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jhc23\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 686, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\jhc23\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\jhc23\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy.linalg

networkSize = 1000
numberOfEdges = 10000
G = nx.gnm_random_graph(networkSize, numberOfEdges)

L = nx.normalized_laplacian_matrix(G)
e = numpy.linalg.eigvals(L.A)
print("Largest eigenvalue:", max(e))
print("Smallest eigenvalue:", min(e))
plt.figure(figsize=(12,9))
plt.hist(e, bins=100, edgecolor='black', linewidth=0.5, rwidth=0.5) 
plt.xlabel('Eigenvalue', fontsize=12)
plt.ylabel('Count', fontsize=12)
plt.show()

------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mAttributeError[0m                            Traceback (most recent call last)
Cell [1;32mIn[22], line 8[0m
[0;32m      5[0m G [38;5;241m=[39m nx[38;5;241m.[39mgnm_random_graph(networkSize, numberOfEdges)
[0;32m      7[0m L [38;5;241m=[39m nx[38;5;241m.[39mnormalized_laplacian_matrix(G)
[1;32m----> 8[0m e [38;5;241m=[39m numpy[38;5;241m.[39mlinalg[38;5;241m.[39meigvals([43mL[49m[38;5;241;43m.[39;49m[43mA[49m)
[0;32m      9[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mLargest eigenvalue:[39m[38;5;124m"[39m, [38;5;28mmax[39m(e))
[0;32m     10[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mSmallest eigenvalue:[39m[38;5;124m"[39m, [38;5;28mmin[39m(e))

[1;31mAttributeError[0m: 'csr_array' object has no attribute 'A'

