Traceback (most recent call last):
  File "C:\Users\jhc23\AppData\Local\Programs\Python\Python312\Lib\site-packages\myst_nb\core\execute\inline.py", line 128, in code_cell_outputs
    self._client.execute_cell(
  File "C:\Users\jhc23\AppData\Roaming\Python\Python312\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jhc23\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 686, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\jhc23\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\jhc23\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
!pip3 install brian2
from brian2 import *
------------------

----- stdout -----
Requirement already satisfied: brian2 in c:\users\jhc23\documents\education\phd\code\python\joao_comp_neuro\compneurocourse\.venv\lib\site-packages (2.8.0.4)
Requirement already satisfied: numpy>=1.23.5 in c:\users\jhc23\documents\education\phd\code\python\joao_comp_neuro\compneurocourse\.venv\lib\site-packages (from brian2) (2.2.5)
Requirement already satisfied: cython>=0.29.21 in c:\users\jhc23\documents\education\phd\code\python\joao_comp_neuro\compneurocourse\.venv\lib\site-packages (from brian2) (3.1.0)
Requirement already satisfied: sympy>=1.2 in c:\users\jhc23\documents\education\phd\code\python\joao_comp_neuro\compneurocourse\.venv\lib\site-packages (from brian2) (1.14.0)
Requirement already satisfied: pyparsing in c:\users\jhc23\documents\education\phd\code\python\joao_comp_neuro\compneurocourse\.venv\lib\site-packages (from brian2) (3.2.3)
Requirement already satisfied: jinja2>=2.7 in c:\users\jhc23\documents\education\phd\code\python\joao_comp_neuro\compneurocourse\.venv\lib\site-packages (from brian2) (3.1.6)
Requirement already satisfied: py-cpuinfo in c:\users\jhc23\documents\education\phd\code\python\joao_comp_neuro\compneurocourse\.venv\lib\site-packages (from brian2) (9.0.0)
Requirement already satisfied: setuptools>=61 in c:\users\jhc23\documents\education\phd\code\python\joao_comp_neuro\compneurocourse\.venv\lib\site-packages (from brian2) (80.3.1)
Requirement already satisfied: packaging in c:\users\jhc23\documents\education\phd\code\python\joao_comp_neuro\compneurocourse\.venv\lib\site-packages (from brian2) (25.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\jhc23\documents\education\phd\code\python\joao_comp_neuro\compneurocourse\.venv\lib\site-packages (from jinja2>=2.7->brian2) (3.0.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\jhc23\documents\education\phd\code\python\joao_comp_neuro\compneurocourse\.venv\lib\site-packages (from sympy>=1.2->brian2) (1.3.0)
----- stderr -----

[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[1], line 2[0m
[0;32m      1[0m get_ipython()[38;5;241m.[39msystem([38;5;124m'[39m[38;5;124mpip3 install brian2[39m[38;5;124m'[39m)
[1;32m----> 2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mbrian2[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m

[1;31mModuleNotFoundError[0m: No module named 'brian2'

